"""美股 directory 种子: 大盘 ETF + 道指 + NASDAQ100 头部 + S&P100 + 中概股。
不调外部 API, 启动期纯本地写库(避开雷区 1 mini_racer)。
"""
from __future__ import annotations

US_SEEDS: list[tuple[str, str, str]] = [
    # 大盘指数 ETF
    ("SPY", "SPDR S&P 500 ETF", "us"),
    ("QQQ", "Invesco QQQ Trust", "us"),
    ("DIA", "SPDR Dow Jones Industrial Average ETF", "us"),
    ("IWM", "iShares Russell 2000 ETF", "us"),
    ("VTI", "Vanguard Total Stock Market ETF", "us"),
    ("VOO", "Vanguard S&P 500 ETF", "us"),
    # 行业 ETF
    ("XLF", "Financial Select Sector SPDR", "us"),
    ("XLK", "Technology Select Sector SPDR", "us"),
    ("XLE", "Energy Select Sector SPDR", "us"),
    ("XLV", "Health Care Select Sector SPDR", "us"),
    ("XLI", "Industrial Select Sector SPDR", "us"),
    ("XLY", "Consumer Discretionary Select Sector SPDR", "us"),
    ("XLP", "Consumer Staples Select Sector SPDR", "us"),
    ("XLU", "Utilities Select Sector SPDR", "us"),
    ("XLB", "Materials Select Sector SPDR", "us"),
    ("XLRE", "Real Estate Select Sector SPDR", "us"),
    ("XLC", "Communication Services Select Sector SPDR", "us"),
    # 主题 ETF
    ("ARKK", "ARK Innovation ETF", "us"),
    ("SMH", "VanEck Semiconductor ETF", "us"),
    ("SOXX", "iShares Semiconductor ETF", "us"),
    ("GLD", "SPDR Gold Shares", "us"),
    ("SLV", "iShares Silver Trust", "us"),
    ("TLT", "iShares 20+ Year Treasury Bond ETF", "us"),
    # 大盘股 (按市值大致排序, 涵盖 NASDAQ100 + DJIA + S&P 头部)
    ("AAPL", "Apple Inc.", "us"),
    ("MSFT", "Microsoft Corporation", "us"),
    ("GOOGL", "Alphabet Inc. Class A", "us"),
    ("GOOG", "Alphabet Inc. Class C", "us"),
    ("AMZN", "Amazon.com Inc.", "us"),
    ("META", "Meta Platforms Inc.", "us"),
    ("NVDA", "NVIDIA Corporation", "us"),
    ("TSLA", "Tesla Inc.", "us"),
    ("BRK.B", "Berkshire Hathaway Inc. Class B", "us"),
    ("AVGO", "Broadcom Inc.", "us"),
    ("JPM", "JPMorgan Chase & Co.", "us"),
    ("V", "Visa Inc.", "us"),
    ("UNH", "UnitedHealth Group Incorporated", "us"),
    ("MA", "Mastercard Incorporated", "us"),
    ("HD", "Home Depot Inc.", "us"),
    ("PG", "Procter & Gamble Co.", "us"),
    ("LLY", "Eli Lilly and Company", "us"),
    ("ORCL", "Oracle Corporation", "us"),
    ("CRM", "Salesforce Inc.", "us"),
    ("COST", "Costco Wholesale Corporation", "us"),
    ("ABBV", "AbbVie Inc.", "us"),
    ("WMT", "Walmart Inc.", "us"),
    ("KO", "Coca-Cola Company", "us"),
    ("PEP", "PepsiCo Inc.", "us"),
    ("BAC", "Bank of America Corporation", "us"),
    ("AMD", "Advanced Micro Devices Inc.", "us"),
    ("ADBE", "Adobe Inc.", "us"),
    ("NFLX", "Netflix Inc.", "us"),
    ("CSCO", "Cisco Systems Inc.", "us"),
    ("MRK", "Merck & Co. Inc.", "us"),
    ("CVX", "Chevron Corporation", "us"),
    ("XOM", "Exxon Mobil Corporation", "us"),
    ("ABT", "Abbott Laboratories", "us"),
    ("TMO", "Thermo Fisher Scientific Inc.", "us"),
    ("ACN", "Accenture plc", "us"),
    ("DHR", "Danaher Corporation", "us"),
    ("DIS", "Walt Disney Company", "us"),
    ("INTC", "Intel Corporation", "us"),
    ("QCOM", "Qualcomm Incorporated", "us"),
    ("TXN", "Texas Instruments Incorporated", "us"),
    ("INTU", "Intuit Inc.", "us"),
    ("AMAT", "Applied Materials Inc.", "us"),
    ("PYPL", "PayPal Holdings Inc.", "us"),
    ("UBER", "Uber Technologies Inc.", "us"),
    ("SHOP", "Shopify Inc.", "us"),
    ("SQ", "Block Inc.", "us"),
    ("PLTR", "Palantir Technologies Inc.", "us"),
    ("COIN", "Coinbase Global Inc.", "us"),
    ("HOOD", "Robinhood Markets Inc.", "us"),
    ("RBLX", "Roblox Corporation", "us"),
    ("U", "Unity Software Inc.", "us"),
    ("SNAP", "Snap Inc.", "us"),
    ("PINS", "Pinterest Inc.", "us"),
    ("ABNB", "Airbnb Inc.", "us"),
    ("DASH", "DoorDash Inc.", "us"),
    ("SNOW", "Snowflake Inc.", "us"),
    ("DDOG", "Datadog Inc.", "us"),
    ("CRWD", "CrowdStrike Holdings Inc.", "us"),
    ("ZS", "Zscaler Inc.", "us"),
    ("NET", "Cloudflare Inc.", "us"),
    ("MDB", "MongoDB Inc.", "us"),
    ("OKTA", "Okta Inc.", "us"),
    ("TEAM", "Atlassian Corporation", "us"),
    ("ZM", "Zoom Video Communications Inc.", "us"),
    ("DOCU", "DocuSign Inc.", "us"),
    ("ROKU", "Roku Inc.", "us"),
    ("SPOT", "Spotify Technology S.A.", "us"),
    ("F", "Ford Motor Company", "us"),
    ("GM", "General Motors Company", "us"),
    ("RIVN", "Rivian Automotive Inc.", "us"),
    ("LCID", "Lucid Group Inc.", "us"),
    ("NIO", "NIO Inc.", "us"),
    ("XPEV", "XPeng Inc.", "us"),
    ("LI", "Li Auto Inc.", "us"),
    ("BABA", "Alibaba Group Holding Limited", "us"),
    ("PDD", "PDD Holdings Inc.", "us"),
    ("JD", "JD.com Inc.", "us"),
    ("BIDU", "Baidu Inc.", "us"),
    ("BILI", "Bilibili Inc.", "us"),
    ("TME", "Tencent Music Entertainment Group", "us"),
    ("IQ", "iQIYI Inc.", "us"),
    ("BA", "Boeing Company", "us"),
    ("CAT", "Caterpillar Inc.", "us"),
    ("GS", "Goldman Sachs Group Inc.", "us"),
    ("MS", "Morgan Stanley", "us"),
    ("WFC", "Wells Fargo & Company", "us"),
    ("C", "Citigroup Inc.", "us"),
    ("AXP", "American Express Company", "us"),
    ("BLK", "BlackRock Inc.", "us"),
    ("SCHW", "Charles Schwab Corporation", "us"),
    ("MCD", "McDonald's Corporation", "us"),
    ("SBUX", "Starbucks Corporation", "us"),
    ("NKE", "Nike Inc.", "us"),
    ("LULU", "Lululemon Athletica Inc.", "us"),
    ("BKNG", "Booking Holdings Inc.", "us"),
    ("MAR", "Marriott International Inc.", "us"),
    ("CMCSA", "Comcast Corporation", "us"),
    ("T", "AT&T Inc.", "us"),
    ("VZ", "Verizon Communications Inc.", "us"),
    ("CVS", "CVS Health Corporation", "us"),
    ("UNP", "Union Pacific Corporation", "us"),
    ("UPS", "United Parcel Service Inc.", "us"),
    ("FDX", "FedEx Corporation", "us"),
    ("HON", "Honeywell International Inc.", "us"),
    ("GE", "General Electric Company", "us"),
    ("LMT", "Lockheed Martin Corporation", "us"),
    ("RTX", "RTX Corporation", "us"),
    ("MMM", "3M Company", "us"),
    ("IBM", "International Business Machines Corporation", "us"),
    ("NOW", "ServiceNow Inc.", "us"),
    ("PANW", "Palo Alto Networks Inc.", "us"),
    ("FTNT", "Fortinet Inc.", "us"),
    ("MU", "Micron Technology Inc.", "us"),
    ("LRCX", "Lam Research Corporation", "us"),
    ("KLAC", "KLA Corporation", "us"),
    ("ASML", "ASML Holding N.V.", "us"),
    ("TSM", "Taiwan Semiconductor Manufacturing Company Limited", "us"),
    ("ARM", "Arm Holdings plc", "us"),
    ("MRVL", "Marvell Technology Inc.", "us"),
    ("ON", "ON Semiconductor Corporation", "us"),
    ("MCHP", "Microchip Technology Incorporated", "us"),
    ("ANET", "Arista Networks Inc.", "us"),
    ("DELL", "Dell Technologies Inc.", "us"),
    ("HPQ", "HP Inc.", "us"),
    ("WBD", "Warner Bros. Discovery Inc.", "us"),
    ("PARA", "Paramount Global", "us"),
]
